In [1]:
import tensorflow as tf
from keras.layers import *
from keras.models import Model,Sequential

Using TensorFlow backend.


In [2]:
model=Sequential()
model=Sequential()
model.add(SeparableConv2D(9,(3,3),padding="same",activation=None,input_shape=(48,48,3)))
model.add(BatchNormalization(axis=-1))
model.add(LeakyReLU(alpha=0.3))

model.add(MaxPooling2D(pool_size=(2,2),strides=None))
model.add(BatchNormalization(axis=-1))

model.add(SeparableConv2D(36,(3,3),padding="same",activation=None))
model.add(BatchNormalization(axis=-1))
model.add(LeakyReLU(alpha=0.3))
          

model.add(MaxPooling2D(pool_size=(2,2),strides=None))
model.add(BatchNormalization(axis=-1))
          
model.add(SeparableConv2D(144,(3,3),padding="same",activation=None))
model.add(LeakyReLU(alpha=0.3))
model.add(BatchNormalization(axis=-1))

model.add(MaxPooling2D(pool_size=(2,2),strides=None))
model.add(BatchNormalization(axis=-1))


model.add(SeparableConv2D(576,(3,3),padding='same',activation=None))
model.add(BatchNormalization(axis=-1))
model.add(LeakyReLU(alpha=0.3))

model.add(MaxPooling2D(pool_size=(2,2),strides=None))
model.add(BatchNormalization(axis=-1))

model.add(SeparableConv2D(2304,(3,3),padding='same',activation=None))
model.add(BatchNormalization(axis=-1))
model.add(LeakyReLU(alpha=0.3))

model.add(MaxPooling2D(pool_size=(3,3),strides=None))
model.add(BatchNormalization(axis=-1))
model.add(Flatten())
model.add(Dense(2304,activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [3]:
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
separable_conv2d_1 (Separabl (None, 48, 48, 9)         63        
_________________________________________________________________
batch_normalization_1 (Batch (None, 48, 48, 9)         36        
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 48, 48, 9)         0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 24, 24, 9)         0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 24, 24, 9)         36        
_________________________________________________________________
separable_conv2d_2 (Separabl (None, 24, 24, 36)        441       
_________________________________________________________________
batch_normalization_3 (Batch (None, 24, 24, 36)        144       
__________

In [4]:
import cv2
import glob
import numpy as np
X_data=[]

In [5]:
import natsort
files=sorted(glob.glob("Sayan/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Sayan/0.png', 'Sayan/1.png', 'Sayan/2.png', 'Sayan/3.png', 'Sayan/4.png', 'Sayan/5.png', 'Sayan/6.png', 'Sayan/7.png', 'Sayan/8.png', 'Sayan/9.png', 'Sayan/10.png', 'Sayan/11.png', 'Sayan/12.png', 'Sayan/13.png', 'Sayan/14.png', 'Sayan/15.png', 'Sayan/16.png', 'Sayan/17.png', 'Sayan/18.png', 'Sayan/19.png', 'Sayan/20.png', 'Sayan/21.png', 'Sayan/22.png', 'Sayan/23.png', 'Sayan/24.png', 'Sayan/25.png', 'Sayan/26.png', 'Sayan/27.png', 'Sayan/28.png', 'Sayan/29.png', 'Sayan/30.png', 'Sayan/31.png', 'Sayan/32.png', 'Sayan/33.png', 'Sayan/34.png', 'Sayan/35.png', 'Sayan/36.png', 'Sayan/37.png', 'Sayan/38.png', 'Sayan/39.png', 'Sayan/40.png', 'Sayan/41.png', 'Sayan/42.png', 'Sayan/43.png', 'Sayan/44.png', 'Sayan/45.png', 'Sayan/46.png', 'Sayan/47.png', 'Sayan/48.png', 'Sayan/49.png', 'Sayan/50.png', 'Sayan/51.png', 'Sayan/52.png', 'Sayan/53.png', 'Sayan/54.png', 'Sayan/55.png', 'Sayan/56.png', 'Sayan/57.png', 'Sayan/58.png', 'Sayan/59.png', 'Sayan/60.png', 'Sayan/61.png', 'Sayan/62.png', '

In [6]:
for f in files:
    print(f)
    im=cv2.imread(f)
    X_data.append(im)

Sayan/0.png
Sayan/1.png
Sayan/2.png
Sayan/3.png
Sayan/4.png
Sayan/5.png
Sayan/6.png
Sayan/7.png
Sayan/8.png
Sayan/9.png
Sayan/10.png
Sayan/11.png
Sayan/12.png
Sayan/13.png
Sayan/14.png
Sayan/15.png
Sayan/16.png
Sayan/17.png
Sayan/18.png
Sayan/19.png
Sayan/20.png
Sayan/21.png
Sayan/22.png
Sayan/23.png
Sayan/24.png
Sayan/25.png
Sayan/26.png
Sayan/27.png
Sayan/28.png
Sayan/29.png
Sayan/30.png
Sayan/31.png
Sayan/32.png
Sayan/33.png
Sayan/34.png
Sayan/35.png
Sayan/36.png
Sayan/37.png
Sayan/38.png
Sayan/39.png
Sayan/40.png
Sayan/41.png
Sayan/42.png
Sayan/43.png
Sayan/44.png
Sayan/45.png
Sayan/46.png
Sayan/47.png
Sayan/48.png
Sayan/49.png
Sayan/50.png
Sayan/51.png
Sayan/52.png
Sayan/53.png
Sayan/54.png
Sayan/55.png
Sayan/56.png
Sayan/57.png
Sayan/58.png
Sayan/59.png
Sayan/60.png
Sayan/61.png
Sayan/62.png
Sayan/63.png
Sayan/64.png
Sayan/65.png
Sayan/66.png
Sayan/67.png
Sayan/68.png
Sayan/69.png
Sayan/70.png
Sayan/71.png
Sayan/72.png
Sayan/73.png
Sayan/74.png
Sayan/75.png
Sayan/76.png
Sayan/77.

Sayan/1598.png
Sayan/1599.png
Sayan/1600.png
Sayan/1601.png
Sayan/1602.png
Sayan/1603.png
Sayan/1604.png
Sayan/1605.png
Sayan/1606.png
Sayan/1607.png
Sayan/1608.png
Sayan/1609.png
Sayan/1610.png
Sayan/1611.png
Sayan/1612.png
Sayan/1613.png
Sayan/1614.png
Sayan/1615.png
Sayan/1616.png
Sayan/1617.png
Sayan/1618.png
Sayan/1619.png
Sayan/1620.png
Sayan/1621.png
Sayan/1622.png
Sayan/1623.png
Sayan/1624.png
Sayan/1625.png
Sayan/1626.png
Sayan/1627.png
Sayan/1628.png
Sayan/1629.png
Sayan/1630.png
Sayan/1631.png
Sayan/1632.png
Sayan/1633.png
Sayan/1634.png
Sayan/1635.png
Sayan/1636.png
Sayan/1637.png
Sayan/1638.png
Sayan/1639.png
Sayan/1640.png
Sayan/1641.png
Sayan/1642.png
Sayan/1643.png
Sayan/1644.png
Sayan/1645.png
Sayan/1646.png
Sayan/1647.png
Sayan/1648.png
Sayan/1649.png
Sayan/1650.png
Sayan/1651.png
Sayan/1652.png
Sayan/1653.png
Sayan/1654.png
Sayan/1655.png
Sayan/1656.png
Sayan/1657.png
Sayan/1658.png
Sayan/1659.png
Sayan/1660.png
Sayan/1661.png
Sayan/1662.png
Sayan/1663.png
Sayan/1664

In [7]:
files=sorted(glob.glob("Rot_Sayan/Sayanrot90/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayan/Sayanrot90/90_0.png', 'Rot_Sayan/Sayanrot90/90_1.png', 'Rot_Sayan/Sayanrot90/90_2.png', 'Rot_Sayan/Sayanrot90/90_3.png', 'Rot_Sayan/Sayanrot90/90_4.png', 'Rot_Sayan/Sayanrot90/90_5.png', 'Rot_Sayan/Sayanrot90/90_6.png', 'Rot_Sayan/Sayanrot90/90_7.png', 'Rot_Sayan/Sayanrot90/90_8.png', 'Rot_Sayan/Sayanrot90/90_9.png', 'Rot_Sayan/Sayanrot90/90_10.png', 'Rot_Sayan/Sayanrot90/90_11.png', 'Rot_Sayan/Sayanrot90/90_12.png', 'Rot_Sayan/Sayanrot90/90_13.png', 'Rot_Sayan/Sayanrot90/90_14.png', 'Rot_Sayan/Sayanrot90/90_15.png', 'Rot_Sayan/Sayanrot90/90_16.png', 'Rot_Sayan/Sayanrot90/90_17.png', 'Rot_Sayan/Sayanrot90/90_18.png', 'Rot_Sayan/Sayanrot90/90_19.png', 'Rot_Sayan/Sayanrot90/90_20.png', 'Rot_Sayan/Sayanrot90/90_21.png', 'Rot_Sayan/Sayanrot90/90_22.png', 'Rot_Sayan/Sayanrot90/90_23.png', 'Rot_Sayan/Sayanrot90/90_24.png', 'Rot_Sayan/Sayanrot90/90_25.png', 'Rot_Sayan/Sayanrot90/90_26.png', 'Rot_Sayan/Sayanrot90/90_27.png', 'Rot_Sayan/Sayanrot90/90_28.png', 'Rot_Sayan/Sayanrot90/9

In [8]:
for f in files:
    print(f)
    im=cv2.imread(f)
    X_data.append(im)

Rot_Sayan/Sayanrot90/90_0.png
Rot_Sayan/Sayanrot90/90_1.png
Rot_Sayan/Sayanrot90/90_2.png
Rot_Sayan/Sayanrot90/90_3.png
Rot_Sayan/Sayanrot90/90_4.png
Rot_Sayan/Sayanrot90/90_5.png
Rot_Sayan/Sayanrot90/90_6.png
Rot_Sayan/Sayanrot90/90_7.png
Rot_Sayan/Sayanrot90/90_8.png
Rot_Sayan/Sayanrot90/90_9.png
Rot_Sayan/Sayanrot90/90_10.png
Rot_Sayan/Sayanrot90/90_11.png
Rot_Sayan/Sayanrot90/90_12.png
Rot_Sayan/Sayanrot90/90_13.png
Rot_Sayan/Sayanrot90/90_14.png
Rot_Sayan/Sayanrot90/90_15.png
Rot_Sayan/Sayanrot90/90_16.png
Rot_Sayan/Sayanrot90/90_17.png
Rot_Sayan/Sayanrot90/90_18.png
Rot_Sayan/Sayanrot90/90_19.png
Rot_Sayan/Sayanrot90/90_20.png
Rot_Sayan/Sayanrot90/90_21.png
Rot_Sayan/Sayanrot90/90_22.png
Rot_Sayan/Sayanrot90/90_23.png
Rot_Sayan/Sayanrot90/90_24.png
Rot_Sayan/Sayanrot90/90_25.png
Rot_Sayan/Sayanrot90/90_26.png
Rot_Sayan/Sayanrot90/90_27.png
Rot_Sayan/Sayanrot90/90_28.png
Rot_Sayan/Sayanrot90/90_29.png
Rot_Sayan/Sayanrot90/90_30.png
Rot_Sayan/Sayanrot90/90_31.png
Rot_Sayan/Sayanrot

Rot_Sayan/Sayanrot90/90_2031.png
Rot_Sayan/Sayanrot90/90_2032.png
Rot_Sayan/Sayanrot90/90_2033.png
Rot_Sayan/Sayanrot90/90_2034.png
Rot_Sayan/Sayanrot90/90_2035.png
Rot_Sayan/Sayanrot90/90_2036.png
Rot_Sayan/Sayanrot90/90_2037.png
Rot_Sayan/Sayanrot90/90_2038.png
Rot_Sayan/Sayanrot90/90_2039.png


In [9]:
files=sorted(glob.glob("Rot_Sayan/Sayanrot180/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayan/Sayanrot180/180_0.png', 'Rot_Sayan/Sayanrot180/180_1.png', 'Rot_Sayan/Sayanrot180/180_2.png', 'Rot_Sayan/Sayanrot180/180_3.png', 'Rot_Sayan/Sayanrot180/180_4.png', 'Rot_Sayan/Sayanrot180/180_5.png', 'Rot_Sayan/Sayanrot180/180_6.png', 'Rot_Sayan/Sayanrot180/180_7.png', 'Rot_Sayan/Sayanrot180/180_8.png', 'Rot_Sayan/Sayanrot180/180_9.png', 'Rot_Sayan/Sayanrot180/180_10.png', 'Rot_Sayan/Sayanrot180/180_11.png', 'Rot_Sayan/Sayanrot180/180_12.png', 'Rot_Sayan/Sayanrot180/180_13.png', 'Rot_Sayan/Sayanrot180/180_14.png', 'Rot_Sayan/Sayanrot180/180_15.png', 'Rot_Sayan/Sayanrot180/180_16.png', 'Rot_Sayan/Sayanrot180/180_17.png', 'Rot_Sayan/Sayanrot180/180_18.png', 'Rot_Sayan/Sayanrot180/180_19.png', 'Rot_Sayan/Sayanrot180/180_20.png', 'Rot_Sayan/Sayanrot180/180_21.png', 'Rot_Sayan/Sayanrot180/180_22.png', 'Rot_Sayan/Sayanrot180/180_23.png', 'Rot_Sayan/Sayanrot180/180_24.png', 'Rot_Sayan/Sayanrot180/180_25.png', 'Rot_Sayan/Sayanrot180/180_26.png', 'Rot_Sayan/Sayanrot180/180_27.png', '

In [10]:
for f in files:
    print(f)
    im=cv2.imread(f)
    X_data.append(im)

Rot_Sayan/Sayanrot180/180_0.png
Rot_Sayan/Sayanrot180/180_1.png
Rot_Sayan/Sayanrot180/180_2.png
Rot_Sayan/Sayanrot180/180_3.png
Rot_Sayan/Sayanrot180/180_4.png
Rot_Sayan/Sayanrot180/180_5.png
Rot_Sayan/Sayanrot180/180_6.png
Rot_Sayan/Sayanrot180/180_7.png
Rot_Sayan/Sayanrot180/180_8.png
Rot_Sayan/Sayanrot180/180_9.png
Rot_Sayan/Sayanrot180/180_10.png
Rot_Sayan/Sayanrot180/180_11.png
Rot_Sayan/Sayanrot180/180_12.png
Rot_Sayan/Sayanrot180/180_13.png
Rot_Sayan/Sayanrot180/180_14.png
Rot_Sayan/Sayanrot180/180_15.png
Rot_Sayan/Sayanrot180/180_16.png
Rot_Sayan/Sayanrot180/180_17.png
Rot_Sayan/Sayanrot180/180_18.png
Rot_Sayan/Sayanrot180/180_19.png
Rot_Sayan/Sayanrot180/180_20.png
Rot_Sayan/Sayanrot180/180_21.png
Rot_Sayan/Sayanrot180/180_22.png
Rot_Sayan/Sayanrot180/180_23.png
Rot_Sayan/Sayanrot180/180_24.png
Rot_Sayan/Sayanrot180/180_25.png
Rot_Sayan/Sayanrot180/180_26.png
Rot_Sayan/Sayanrot180/180_27.png
Rot_Sayan/Sayanrot180/180_28.png
Rot_Sayan/Sayanrot180/180_29.png
Rot_Sayan/Sayanrot18

Rot_Sayan/Sayanrot180/180_1708.png
Rot_Sayan/Sayanrot180/180_1709.png
Rot_Sayan/Sayanrot180/180_1710.png
Rot_Sayan/Sayanrot180/180_1711.png
Rot_Sayan/Sayanrot180/180_1712.png
Rot_Sayan/Sayanrot180/180_1713.png
Rot_Sayan/Sayanrot180/180_1714.png
Rot_Sayan/Sayanrot180/180_1715.png
Rot_Sayan/Sayanrot180/180_1716.png
Rot_Sayan/Sayanrot180/180_1717.png
Rot_Sayan/Sayanrot180/180_1718.png
Rot_Sayan/Sayanrot180/180_1719.png
Rot_Sayan/Sayanrot180/180_1720.png
Rot_Sayan/Sayanrot180/180_1721.png
Rot_Sayan/Sayanrot180/180_1722.png
Rot_Sayan/Sayanrot180/180_1723.png
Rot_Sayan/Sayanrot180/180_1724.png
Rot_Sayan/Sayanrot180/180_1725.png
Rot_Sayan/Sayanrot180/180_1726.png
Rot_Sayan/Sayanrot180/180_1727.png
Rot_Sayan/Sayanrot180/180_1728.png
Rot_Sayan/Sayanrot180/180_1729.png
Rot_Sayan/Sayanrot180/180_1730.png
Rot_Sayan/Sayanrot180/180_1731.png
Rot_Sayan/Sayanrot180/180_1732.png
Rot_Sayan/Sayanrot180/180_1733.png
Rot_Sayan/Sayanrot180/180_1734.png
Rot_Sayan/Sayanrot180/180_1735.png
Rot_Sayan/Sayanrot18

In [11]:
files=sorted(glob.glob("Rot_Sayan/Sayanrot270/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayan/Sayanrot270/270_0.png', 'Rot_Sayan/Sayanrot270/270_1.png', 'Rot_Sayan/Sayanrot270/270_2.png', 'Rot_Sayan/Sayanrot270/270_3.png', 'Rot_Sayan/Sayanrot270/270_4.png', 'Rot_Sayan/Sayanrot270/270_5.png', 'Rot_Sayan/Sayanrot270/270_6.png', 'Rot_Sayan/Sayanrot270/270_7.png', 'Rot_Sayan/Sayanrot270/270_8.png', 'Rot_Sayan/Sayanrot270/270_9.png', 'Rot_Sayan/Sayanrot270/270_10.png', 'Rot_Sayan/Sayanrot270/270_11.png', 'Rot_Sayan/Sayanrot270/270_12.png', 'Rot_Sayan/Sayanrot270/270_13.png', 'Rot_Sayan/Sayanrot270/270_14.png', 'Rot_Sayan/Sayanrot270/270_15.png', 'Rot_Sayan/Sayanrot270/270_16.png', 'Rot_Sayan/Sayanrot270/270_17.png', 'Rot_Sayan/Sayanrot270/270_18.png', 'Rot_Sayan/Sayanrot270/270_19.png', 'Rot_Sayan/Sayanrot270/270_20.png', 'Rot_Sayan/Sayanrot270/270_21.png', 'Rot_Sayan/Sayanrot270/270_22.png', 'Rot_Sayan/Sayanrot270/270_23.png', 'Rot_Sayan/Sayanrot270/270_24.png', 'Rot_Sayan/Sayanrot270/270_25.png', 'Rot_Sayan/Sayanrot270/270_26.png', 'Rot_Sayan/Sayanrot270/270_27.png', '

In [12]:
for f in files:
    print(f)
    im=cv2.imread(f)
    X_data.append(im)

Rot_Sayan/Sayanrot270/270_0.png
Rot_Sayan/Sayanrot270/270_1.png
Rot_Sayan/Sayanrot270/270_2.png
Rot_Sayan/Sayanrot270/270_3.png
Rot_Sayan/Sayanrot270/270_4.png
Rot_Sayan/Sayanrot270/270_5.png
Rot_Sayan/Sayanrot270/270_6.png
Rot_Sayan/Sayanrot270/270_7.png
Rot_Sayan/Sayanrot270/270_8.png
Rot_Sayan/Sayanrot270/270_9.png
Rot_Sayan/Sayanrot270/270_10.png
Rot_Sayan/Sayanrot270/270_11.png
Rot_Sayan/Sayanrot270/270_12.png
Rot_Sayan/Sayanrot270/270_13.png
Rot_Sayan/Sayanrot270/270_14.png
Rot_Sayan/Sayanrot270/270_15.png
Rot_Sayan/Sayanrot270/270_16.png
Rot_Sayan/Sayanrot270/270_17.png
Rot_Sayan/Sayanrot270/270_18.png
Rot_Sayan/Sayanrot270/270_19.png
Rot_Sayan/Sayanrot270/270_20.png
Rot_Sayan/Sayanrot270/270_21.png
Rot_Sayan/Sayanrot270/270_22.png
Rot_Sayan/Sayanrot270/270_23.png
Rot_Sayan/Sayanrot270/270_24.png
Rot_Sayan/Sayanrot270/270_25.png
Rot_Sayan/Sayanrot270/270_26.png
Rot_Sayan/Sayanrot270/270_27.png
Rot_Sayan/Sayanrot270/270_28.png
Rot_Sayan/Sayanrot270/270_29.png
Rot_Sayan/Sayanrot27

Rot_Sayan/Sayanrot270/270_1757.png
Rot_Sayan/Sayanrot270/270_1758.png
Rot_Sayan/Sayanrot270/270_1759.png
Rot_Sayan/Sayanrot270/270_1760.png
Rot_Sayan/Sayanrot270/270_1761.png
Rot_Sayan/Sayanrot270/270_1762.png
Rot_Sayan/Sayanrot270/270_1763.png
Rot_Sayan/Sayanrot270/270_1764.png
Rot_Sayan/Sayanrot270/270_1765.png
Rot_Sayan/Sayanrot270/270_1766.png
Rot_Sayan/Sayanrot270/270_1767.png
Rot_Sayan/Sayanrot270/270_1768.png
Rot_Sayan/Sayanrot270/270_1769.png
Rot_Sayan/Sayanrot270/270_1770.png
Rot_Sayan/Sayanrot270/270_1771.png
Rot_Sayan/Sayanrot270/270_1772.png
Rot_Sayan/Sayanrot270/270_1773.png
Rot_Sayan/Sayanrot270/270_1774.png
Rot_Sayan/Sayanrot270/270_1775.png
Rot_Sayan/Sayanrot270/270_1776.png
Rot_Sayan/Sayanrot270/270_1777.png
Rot_Sayan/Sayanrot270/270_1778.png
Rot_Sayan/Sayanrot270/270_1779.png
Rot_Sayan/Sayanrot270/270_1780.png
Rot_Sayan/Sayanrot270/270_1781.png
Rot_Sayan/Sayanrot270/270_1782.png
Rot_Sayan/Sayanrot270/270_1783.png
Rot_Sayan/Sayanrot270/270_1784.png
Rot_Sayan/Sayanrot27

In [13]:
np.array(X_data).shape

(8160, 48, 48, 3)

In [14]:
Y=[]
files2 = sorted(glob.glob ("Sayanbandw/*.png"))
files2=(natsort.natsorted(files2,reverse=False))
for myFile in files2:
    im=cv2.imread(myFile,cv2.IMREAD_GRAYSCALE)
    Y.append(im)

In [15]:
files=sorted(glob.glob("Rot_Sayanbandw/Rot_Sayanbandw90/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayanbandw/Rot_Sayanbandw90/90_0.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_1.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_2.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_3.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_4.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_5.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_6.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_7.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_8.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_9.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_10.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_11.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_12.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_13.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_14.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_15.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_16.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_17.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_18.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_19.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_20.png', 'Rot_Sayanbandw/Rot_Sayanbandw90/90_21.png', 'Rot_Sayanbandw/Rot

In [16]:
for myFile in files:
    im=cv2.imread(myFile,cv2.IMREAD_GRAYSCALE)
    Y.append(im)

In [17]:
files=sorted(glob.glob("Rot_Sayanbandw/Rot_Sayanbandw180/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayanbandw/Rot_Sayanbandw180/180_0.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_1.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_2.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_3.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_4.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_5.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_6.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_7.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_8.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_9.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_10.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_11.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_12.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_13.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_14.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_15.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_16.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_17.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_18.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_19.png', 'Rot_Sayanbandw/Rot_Sayanbandw180/180_20.png', 'Rot_Sayanbandw/Rot_Sa

In [18]:
for myFile in files:
    im=cv2.imread(myFile,cv2.IMREAD_GRAYSCALE)
    Y.append(im)

In [19]:
files=sorted(glob.glob("Rot_Sayanbandw/Rot_Sayanbandw270/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Rot_Sayanbandw/Rot_Sayanbandw270/270_0.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_1.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_2.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_3.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_4.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_5.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_6.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_7.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_8.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_9.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_10.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_11.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_12.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_13.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_14.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_15.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_16.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_17.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_18.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_19.png', 'Rot_Sayanbandw/Rot_Sayanbandw270/270_20.png', 'Rot_Sayanbandw/Rot_Sa

In [20]:
for myFile in files:
    im=cv2.imread(myFile,cv2.IMREAD_GRAYSCALE)
    print (im)
    Y.append(im)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ..

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255

In [21]:
x=np.array(X_data)

In [22]:
y=np.array(Y)
y=y/255


In [23]:
y.shape


(8160, 48, 48)

In [24]:
y.resize(8160,2304)

In [25]:
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [26]:
history=model.fit(x,y,epochs=5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
8160/8160 [==============================] - 6s 778us/step - loss: 0.3931 - acc: 0.8232
Epoch 2/5
8160/8160 [==============================] - 4s 533us/step - loss: 0.3062 - acc: 0.8678
Epoch 3/5
8160/8160 [==============================] - 4s 536us/step - loss: 0.2547 - acc: 0.8927
Epoch 4/5
8160/8160 [==============================] - 4s 532us/step - loss: 0.1962 - acc: 0.9218
Epoch 5/5
8160/8160 [==============================] - 4s 533us/step - loss: 0.1479 - acc: 0.9438


In [27]:
import matplotlib.pyplot as plt
plt.plot(history.history['acc'])

plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

<Figure size 640x480 with 1 Axes>

In [44]:
files=sorted(glob.glob("Sayanp/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Sayanp/0.png', 'Sayanp/1.png', 'Sayanp/2.png', 'Sayanp/3.png', 'Sayanp/4.png', 'Sayanp/5.png', 'Sayanp/6.png', 'Sayanp/7.png', 'Sayanp/8.png', 'Sayanp/9.png', 'Sayanp/10.png', 'Sayanp/11.png', 'Sayanp/12.png', 'Sayanp/13.png', 'Sayanp/14.png', 'Sayanp/15.png', 'Sayanp/16.png', 'Sayanp/17.png', 'Sayanp/18.png', 'Sayanp/19.png', 'Sayanp/20.png', 'Sayanp/21.png', 'Sayanp/22.png', 'Sayanp/23.png', 'Sayanp/24.png', 'Sayanp/25.png', 'Sayanp/26.png', 'Sayanp/27.png', 'Sayanp/28.png', 'Sayanp/29.png', 'Sayanp/30.png', 'Sayanp/31.png', 'Sayanp/32.png', 'Sayanp/33.png', 'Sayanp/34.png', 'Sayanp/35.png', 'Sayanp/36.png', 'Sayanp/37.png', 'Sayanp/38.png', 'Sayanp/39.png', 'Sayanp/40.png', 'Sayanp/41.png', 'Sayanp/42.png', 'Sayanp/43.png', 'Sayanp/44.png', 'Sayanp/45.png', 'Sayanp/46.png', 'Sayanp/47.png', 'Sayanp/48.png', 'Sayanp/49.png', 'Sayanp/50.png', 'Sayanp/51.png', 'Sayanp/52.png', 'Sayanp/53.png', 'Sayanp/54.png', 'Sayanp/55.png', 'Sayanp/56.png', 'Sayanp/57.png', 'Sayanp/58.png', 'Sayan

In [45]:
X_test=[]
for f in files:
    print(f)
    im=cv2.imread(f)
    X_test.append(im)

Sayanp/0.png
Sayanp/1.png
Sayanp/2.png
Sayanp/3.png
Sayanp/4.png
Sayanp/5.png
Sayanp/6.png
Sayanp/7.png
Sayanp/8.png
Sayanp/9.png
Sayanp/10.png
Sayanp/11.png
Sayanp/12.png
Sayanp/13.png
Sayanp/14.png
Sayanp/15.png
Sayanp/16.png
Sayanp/17.png
Sayanp/18.png
Sayanp/19.png
Sayanp/20.png
Sayanp/21.png
Sayanp/22.png
Sayanp/23.png
Sayanp/24.png
Sayanp/25.png
Sayanp/26.png
Sayanp/27.png
Sayanp/28.png
Sayanp/29.png
Sayanp/30.png
Sayanp/31.png
Sayanp/32.png
Sayanp/33.png
Sayanp/34.png
Sayanp/35.png
Sayanp/36.png
Sayanp/37.png
Sayanp/38.png
Sayanp/39.png
Sayanp/40.png
Sayanp/41.png
Sayanp/42.png
Sayanp/43.png
Sayanp/44.png
Sayanp/45.png
Sayanp/46.png
Sayanp/47.png
Sayanp/48.png
Sayanp/49.png
Sayanp/50.png
Sayanp/51.png
Sayanp/52.png
Sayanp/53.png
Sayanp/54.png
Sayanp/55.png
Sayanp/56.png
Sayanp/57.png
Sayanp/58.png
Sayanp/59.png
Sayanp/60.png
Sayanp/61.png
Sayanp/62.png
Sayanp/63.png
Sayanp/64.png
Sayanp/65.png
Sayanp/66.png
Sayanp/67.png
Sayanp/68.png
Sayanp/69.png
Sayanp/70.png
Sayanp/71.png
Sa

Sayanp/590.png
Sayanp/591.png
Sayanp/592.png
Sayanp/593.png
Sayanp/594.png
Sayanp/595.png
Sayanp/596.png
Sayanp/597.png
Sayanp/598.png
Sayanp/599.png
Sayanp/600.png
Sayanp/601.png
Sayanp/602.png
Sayanp/603.png
Sayanp/604.png
Sayanp/605.png
Sayanp/606.png
Sayanp/607.png
Sayanp/608.png
Sayanp/609.png
Sayanp/610.png
Sayanp/611.png
Sayanp/612.png
Sayanp/613.png
Sayanp/614.png
Sayanp/615.png
Sayanp/616.png
Sayanp/617.png
Sayanp/618.png
Sayanp/619.png
Sayanp/620.png
Sayanp/621.png
Sayanp/622.png
Sayanp/623.png
Sayanp/624.png
Sayanp/625.png
Sayanp/626.png
Sayanp/627.png
Sayanp/628.png
Sayanp/629.png
Sayanp/630.png
Sayanp/631.png
Sayanp/632.png
Sayanp/633.png
Sayanp/634.png
Sayanp/635.png
Sayanp/636.png
Sayanp/637.png
Sayanp/638.png
Sayanp/639.png
Sayanp/640.png
Sayanp/641.png
Sayanp/642.png
Sayanp/643.png
Sayanp/644.png
Sayanp/645.png
Sayanp/646.png
Sayanp/647.png
Sayanp/648.png
Sayanp/649.png
Sayanp/650.png
Sayanp/651.png
Sayanp/652.png
Sayanp/653.png
Sayanp/654.png
Sayanp/655.png
Sayanp/656

Sayanp/1253.png
Sayanp/1254.png
Sayanp/1255.png
Sayanp/1256.png
Sayanp/1257.png
Sayanp/1258.png
Sayanp/1259.png
Sayanp/1260.png
Sayanp/1261.png
Sayanp/1262.png
Sayanp/1263.png
Sayanp/1264.png
Sayanp/1265.png
Sayanp/1266.png
Sayanp/1267.png
Sayanp/1268.png
Sayanp/1269.png
Sayanp/1270.png
Sayanp/1271.png
Sayanp/1272.png
Sayanp/1273.png
Sayanp/1274.png
Sayanp/1275.png
Sayanp/1276.png
Sayanp/1277.png
Sayanp/1278.png
Sayanp/1279.png
Sayanp/1280.png
Sayanp/1281.png
Sayanp/1282.png
Sayanp/1283.png
Sayanp/1284.png
Sayanp/1285.png
Sayanp/1286.png
Sayanp/1287.png
Sayanp/1288.png
Sayanp/1289.png
Sayanp/1290.png
Sayanp/1291.png
Sayanp/1292.png
Sayanp/1293.png
Sayanp/1294.png
Sayanp/1295.png
Sayanp/1296.png
Sayanp/1297.png
Sayanp/1298.png
Sayanp/1299.png
Sayanp/1300.png
Sayanp/1301.png
Sayanp/1302.png
Sayanp/1303.png
Sayanp/1304.png
Sayanp/1305.png
Sayanp/1306.png
Sayanp/1307.png
Sayanp/1308.png
Sayanp/1309.png
Sayanp/1310.png
Sayanp/1311.png
Sayanp/1312.png
Sayanp/1313.png
Sayanp/1314.png
Sayanp/1

In [54]:
x_test=np.array(X_test)
print(x_test)

[[[[214 211 143]
   [214 208 133]
   [210 201 121]
   ...
   [ 47  25  19]
   [ 47  26  18]
   [ 49  30  22]]

  [[209 188 150]
   [215 192 146]
   [210 190 135]
   ...
   [ 43  25  18]
   [ 41  24  15]
   [ 44  27  18]]

  [[212 165 161]
   [218 176 164]
   [211 175 157]
   ...
   [ 38  25  17]
   [ 34  22  12]
   [ 37  25  15]]

  ...

  [[231 198 152]
   [239 213 167]
   [238 218 171]
   ...
   [ 33  35  23]
   [ 39  37  27]
   [ 44  36  29]]

  [[226 189 161]
   [224 194 165]
   [240 219 191]
   ...
   [ 28  35  20]
   [ 37  39  27]
   [ 42  40  30]]

  [[227 186 171]
   [211 178 162]
   [240 217 201]
   ...
   [ 24  34  17]
   [ 26  30  18]
   [ 37  36  26]]]


 [[[ 41  23  30]
   [ 46  29  33]
   [ 34  17  20]
   ...
   [ 44  27  30]
   [ 45  31  32]
   [ 40  28  28]]

  [[ 38  21  25]
   [ 44  27  31]
   [ 38  21  24]
   ...
   [ 43  26  29]
   [ 44  30  31]
   [ 39  27  25]]

  [[ 34  19  23]
   [ 39  25  27]
   [ 38  24  25]
   ...
   [ 43  26  29]
   [ 42  28  29]
   [ 36  24

In [55]:
x_test.shape
x_test=x_test/255

In [48]:
files=sorted(glob.glob("Sayanbandw/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Sayanbandw/0.png', 'Sayanbandw/1.png', 'Sayanbandw/2.png', 'Sayanbandw/3.png', 'Sayanbandw/4.png', 'Sayanbandw/5.png', 'Sayanbandw/6.png', 'Sayanbandw/7.png', 'Sayanbandw/8.png', 'Sayanbandw/9.png', 'Sayanbandw/10.png', 'Sayanbandw/11.png', 'Sayanbandw/12.png', 'Sayanbandw/13.png', 'Sayanbandw/14.png', 'Sayanbandw/15.png', 'Sayanbandw/16.png', 'Sayanbandw/17.png', 'Sayanbandw/18.png', 'Sayanbandw/19.png', 'Sayanbandw/20.png', 'Sayanbandw/21.png', 'Sayanbandw/22.png', 'Sayanbandw/23.png', 'Sayanbandw/24.png', 'Sayanbandw/25.png', 'Sayanbandw/26.png', 'Sayanbandw/27.png', 'Sayanbandw/28.png', 'Sayanbandw/29.png', 'Sayanbandw/30.png', 'Sayanbandw/31.png', 'Sayanbandw/32.png', 'Sayanbandw/33.png', 'Sayanbandw/34.png', 'Sayanbandw/35.png', 'Sayanbandw/36.png', 'Sayanbandw/37.png', 'Sayanbandw/38.png', 'Sayanbandw/39.png', 'Sayanbandw/40.png', 'Sayanbandw/41.png', 'Sayanbandw/42.png', 'Sayanbandw/43.png', 'Sayanbandw/44.png', 'Sayanbandw/45.png', 'Sayanbandw/46.png', 'Sayanbandw/47.png', '

In [49]:
Y_test=[]
for f in files:
    print(f)
    im=cv2.imread(f,cv2.IMREAD_GRAYSCALE)
    Y_test.append(im)

Sayanbandw/0.png
Sayanbandw/1.png
Sayanbandw/2.png
Sayanbandw/3.png
Sayanbandw/4.png
Sayanbandw/5.png
Sayanbandw/6.png
Sayanbandw/7.png
Sayanbandw/8.png
Sayanbandw/9.png
Sayanbandw/10.png
Sayanbandw/11.png
Sayanbandw/12.png
Sayanbandw/13.png
Sayanbandw/14.png
Sayanbandw/15.png
Sayanbandw/16.png
Sayanbandw/17.png
Sayanbandw/18.png
Sayanbandw/19.png
Sayanbandw/20.png
Sayanbandw/21.png
Sayanbandw/22.png
Sayanbandw/23.png
Sayanbandw/24.png
Sayanbandw/25.png
Sayanbandw/26.png
Sayanbandw/27.png
Sayanbandw/28.png
Sayanbandw/29.png
Sayanbandw/30.png
Sayanbandw/31.png
Sayanbandw/32.png
Sayanbandw/33.png
Sayanbandw/34.png
Sayanbandw/35.png
Sayanbandw/36.png
Sayanbandw/37.png
Sayanbandw/38.png
Sayanbandw/39.png
Sayanbandw/40.png
Sayanbandw/41.png
Sayanbandw/42.png
Sayanbandw/43.png
Sayanbandw/44.png
Sayanbandw/45.png
Sayanbandw/46.png
Sayanbandw/47.png
Sayanbandw/48.png
Sayanbandw/49.png
Sayanbandw/50.png
Sayanbandw/51.png
Sayanbandw/52.png
Sayanbandw/53.png
Sayanbandw/54.png
Sayanbandw/55.png
Sa

In [59]:
y_test=np.array(Y_test)

In [61]:
y_test.shape
print(y_test)

[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0 255 255 ...   0   0   0]
  ...
  [255 255 255 ...   0   0   0]
  [255 255 255 ...   0   0   0]
  [255 255 255 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

In [62]:
y_test.resize(2040,2304)
y_test=y_test/255

In [187]:
X_train=x[:2040,:,:]
Y_train=y[:2040,:]
print(X_train.shape)
print (Y_train.shape)

(2040, 48, 48, 3)
(2040, 2304)


In [190]:
l=model.predict(X_train)

In [191]:
print(l)

[[3.9726457e-01 4.5701906e-01 5.2120203e-01 ... 6.3708943e-01
  7.1490556e-01 8.0507255e-01]
 [5.4376781e-02 2.5072783e-02 9.3657196e-02 ... 2.0216033e-01
  2.4801019e-01 1.6258627e-01]
 [8.0463856e-02 5.8429986e-02 4.6403408e-02 ... 1.2925220e-01
  1.0741794e-01 9.2106700e-02]
 ...
 [5.9604645e-08 2.9802322e-08 8.9406967e-08 ... 1.7881393e-07
  9.5367432e-07 2.0265579e-06]
 [6.8545341e-07 2.3841858e-07 2.9802322e-07 ... 3.7729740e-05
  7.5489283e-05 8.1151724e-05]
 [1.2992311e-01 8.6005419e-02 7.4313939e-02 ... 4.3123960e-05
  1.4722347e-05 6.7502260e-05]]


In [192]:
scores = model.evaluate(X_train,Y_train, verbose=1)

2040/2040 [==============================] - 0s 236us/step


In [193]:
print(scores)

[0.24876686737817877, 0.8952367539499321]


In [194]:
l.shape
print(l[0][:])

[0.39726457 0.45701906 0.521202   ... 0.63708943 0.71490556 0.80507255]


In [195]:
labels = (l > 0.5).astype(np.int)

In [148]:
print (labels[0][:])
c=0
for m in range(2304):
    if(labels[0][m]==1):
        c=c+1
print (c)

[0 0 0 ... 0 0 0]
788


In [149]:
print (Y_train[80][:])
c=0
for m in range(2304):
    if(Y_train[0][m]==1):
        c=c+1
print (c)

[1. 1. 1. ... 1. 1. 1.]
966


In [196]:
labels.resize(2040,48,48)

In [197]:
c=0
for i in range(0,48):
    for j in range(0,48):
        if(labels[0][i][j]==1):
            c=c+1
print(c)
print (labels[0,:,:])

1780
[[0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [198]:
final=np.ndarray((1920,2448))
final.shape

        

(1920, 2448)

In [199]:
#Reconstruction of the predicted image
z=0
y1=0
for k in range(0,40):
    for l in range(0,51):
        for i in range(0,48):
            for j in range(0,48):
                final[i+y1][j+l*48]=labels[z][i][j]
        z=z+1
    y1=k*48
print(z)
print(y1)


2040
1872


In [169]:
c=0
for i in range(0,48):
    for j in range(0,48):
        if(final[i][j]==1):
            c=c+1
print(c)

2102


In [40]:
final.shape


(1920, 2448)

In [200]:
final.resize(1920,2448,1)

In [201]:
final=final*255

In [202]:
cv2.imwrite("filetrain100.png",final)

True

In [174]:

labels.shape

(2040, 48, 48)

In [175]:
Y_train.shape

(2040, 2304)

In [176]:
labels.resize(2040,2304)

In [178]:
d=0
for i in range(2040):
    for j in range(2304):
        if(Y_train[i][j]==labels[i][j]):
            d=d+1
dice_score=d/(2304*2040)

In [179]:
print(dice_score)

0.9646371612881264


In [63]:
l1=model.predict(x_test)

In [64]:
scores1 = model.evaluate(x_test,y_test, verbose=1)

2040/2040 [==============================] - 0s 134us/step


In [65]:
print(scores1)

[1.2327127318756252, 0.7040485819180806]


In [66]:
labels1= (l1 > 0.5).astype(np.int)

In [67]:
labels1.resize(2040,48,48)

In [68]:
final1=np.ndarray((1920,2448))
final1.shape

(1920, 2448)

In [69]:
z=0
y1=0
for k in range(0,40):
    for l in range(0,51):
        for i in range(0,48):
            for j in range(0,48):
                final1[i+y1][j+l*48]=labels1[z][i][j]
        z=z+1
    y1=k*48
print(z)
print(y1)


2040
1872


In [70]:
cv2.imwrite("filetrain4.png",final1*255)

True

In [207]:
y_test.shape

(2040, 2304)

In [209]:
labels1.shape

(2040, 48, 48)

In [210]:
labels1.resize(2040,2304)

In [211]:
d=0
for i in range(2040):
    for j in range(2304):
        if(y_test[i][j]==labels1[i][j]):
            d=d+1
dice_score=d/(2304*2040)

In [212]:
print(dice_score)

0.2971258425245098


In [28]:
files=sorted(glob.glob("Sayan2/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Sayan2/img0.png', 'Sayan2/img1.png', 'Sayan2/img2.png', 'Sayan2/img3.png', 'Sayan2/img4.png', 'Sayan2/img5.png', 'Sayan2/img6.png', 'Sayan2/img7.png', 'Sayan2/img8.png', 'Sayan2/img9.png', 'Sayan2/img10.png', 'Sayan2/img11.png', 'Sayan2/img12.png', 'Sayan2/img13.png', 'Sayan2/img14.png', 'Sayan2/img15.png', 'Sayan2/img16.png', 'Sayan2/img17.png', 'Sayan2/img18.png', 'Sayan2/img19.png', 'Sayan2/img20.png', 'Sayan2/img21.png', 'Sayan2/img22.png', 'Sayan2/img23.png', 'Sayan2/img24.png', 'Sayan2/img25.png', 'Sayan2/img26.png', 'Sayan2/img27.png', 'Sayan2/img28.png', 'Sayan2/img29.png', 'Sayan2/img30.png', 'Sayan2/img31.png', 'Sayan2/img32.png', 'Sayan2/img33.png', 'Sayan2/img34.png', 'Sayan2/img35.png', 'Sayan2/img36.png', 'Sayan2/img37.png', 'Sayan2/img38.png', 'Sayan2/img39.png', 'Sayan2/img40.png', 'Sayan2/img41.png', 'Sayan2/img42.png', 'Sayan2/img43.png', 'Sayan2/img44.png', 'Sayan2/img45.png', 'Sayan2/img46.png', 'Sayan2/img47.png', 'Sayan2/img48.png', 'Sayan2/img49.png', 'Sayan2/i

In [29]:
X_test1=[]
for f in files:
    print(f)
    im=cv2.imread(f)
    X_test1.append(im)

Sayan2/img0.png
Sayan2/img1.png
Sayan2/img2.png
Sayan2/img3.png
Sayan2/img4.png
Sayan2/img5.png
Sayan2/img6.png
Sayan2/img7.png
Sayan2/img8.png
Sayan2/img9.png
Sayan2/img10.png
Sayan2/img11.png
Sayan2/img12.png
Sayan2/img13.png
Sayan2/img14.png
Sayan2/img15.png
Sayan2/img16.png
Sayan2/img17.png
Sayan2/img18.png
Sayan2/img19.png
Sayan2/img20.png
Sayan2/img21.png
Sayan2/img22.png
Sayan2/img23.png
Sayan2/img24.png
Sayan2/img25.png
Sayan2/img26.png
Sayan2/img27.png
Sayan2/img28.png
Sayan2/img29.png
Sayan2/img30.png
Sayan2/img31.png
Sayan2/img32.png
Sayan2/img33.png
Sayan2/img34.png
Sayan2/img35.png
Sayan2/img36.png
Sayan2/img37.png
Sayan2/img38.png
Sayan2/img39.png
Sayan2/img40.png
Sayan2/img41.png
Sayan2/img42.png
Sayan2/img43.png
Sayan2/img44.png
Sayan2/img45.png
Sayan2/img46.png
Sayan2/img47.png
Sayan2/img48.png
Sayan2/img49.png
Sayan2/img50.png
Sayan2/img51.png
Sayan2/img52.png
Sayan2/img53.png
Sayan2/img54.png
Sayan2/img55.png
Sayan2/img56.png
Sayan2/img57.png
Sayan2/img58.png
Sayan2/

Sayan2/img1817.png
Sayan2/img1818.png
Sayan2/img1819.png
Sayan2/img1820.png
Sayan2/img1821.png
Sayan2/img1822.png
Sayan2/img1823.png
Sayan2/img1824.png
Sayan2/img1825.png
Sayan2/img1826.png
Sayan2/img1827.png
Sayan2/img1828.png
Sayan2/img1829.png
Sayan2/img1830.png
Sayan2/img1831.png
Sayan2/img1832.png
Sayan2/img1833.png
Sayan2/img1834.png
Sayan2/img1835.png
Sayan2/img1836.png
Sayan2/img1837.png
Sayan2/img1838.png
Sayan2/img1839.png
Sayan2/img1840.png
Sayan2/img1841.png
Sayan2/img1842.png
Sayan2/img1843.png
Sayan2/img1844.png
Sayan2/img1845.png
Sayan2/img1846.png
Sayan2/img1847.png
Sayan2/img1848.png
Sayan2/img1849.png
Sayan2/img1850.png
Sayan2/img1851.png
Sayan2/img1852.png
Sayan2/img1853.png
Sayan2/img1854.png
Sayan2/img1855.png
Sayan2/img1856.png
Sayan2/img1857.png
Sayan2/img1858.png
Sayan2/img1859.png
Sayan2/img1860.png
Sayan2/img1861.png
Sayan2/img1862.png
Sayan2/img1863.png
Sayan2/img1864.png
Sayan2/img1865.png
Sayan2/img1866.png
Sayan2/img1867.png
Sayan2/img1868.png
Sayan2/img18

In [30]:
x_test1=np.array(X_test1)

In [31]:
print(x_test1)

[[[[133 121 139]
   [141 128 144]
   [156 142 154]
   ...
   [109 132 140]
   [107 123 136]
   [ 98 109 123]]

  [[141 136 157]
   [138 134 153]
   [145 140 155]
   ...
   [103 117 129]
   [ 80  84 102]
   [ 83  82 102]]

  [[138 148 172]
   [134 142 165]
   [135 145 163]
   ...
   [113 111 130]
   [ 65  52  76]
   [ 89  70  97]]

  ...

  [[138 130 141]
   [141 133 144]
   [141 137 143]
   ...
   [100 119 132]
   [ 95 114 122]
   [ 89 108 115]]

  [[142 131 141]
   [141 132 142]
   [141 134 141]
   ...
   [103 113 120]
   [115 124 121]
   [115 123 116]]

  [[142 128 139]
   [144 133 141]
   [147 140 145]
   ...
   [122 127 128]
   [127 131 120]
   [111 114  98]]]


 [[[134 100 130]
   [133 103 138]
   [117  96 135]
   ...
   [147 140 153]
   [127 114 128]
   [116  99 120]]

  [[118  68 110]
   [122  79 124]
   [115  80 130]
   ...
   [146 146 160]
   [148 141 154]
   [132 122 138]]

  [[107  42  81]
   [118  58  98]
   [116  68 110]
   ...
   [149 157 174]
   [141 147 158]
   [136 139

In [32]:
files=sorted(glob.glob("Sayan2bandw/*.png"))
files=(natsort.natsorted(files,reverse=False))
print (files)

['Sayan2bandw/img0.png', 'Sayan2bandw/img1.png', 'Sayan2bandw/img2.png', 'Sayan2bandw/img3.png', 'Sayan2bandw/img4.png', 'Sayan2bandw/img5.png', 'Sayan2bandw/img6.png', 'Sayan2bandw/img7.png', 'Sayan2bandw/img8.png', 'Sayan2bandw/img9.png', 'Sayan2bandw/img10.png', 'Sayan2bandw/img11.png', 'Sayan2bandw/img12.png', 'Sayan2bandw/img13.png', 'Sayan2bandw/img14.png', 'Sayan2bandw/img15.png', 'Sayan2bandw/img16.png', 'Sayan2bandw/img17.png', 'Sayan2bandw/img18.png', 'Sayan2bandw/img19.png', 'Sayan2bandw/img20.png', 'Sayan2bandw/img21.png', 'Sayan2bandw/img22.png', 'Sayan2bandw/img23.png', 'Sayan2bandw/img24.png', 'Sayan2bandw/img25.png', 'Sayan2bandw/img26.png', 'Sayan2bandw/img27.png', 'Sayan2bandw/img28.png', 'Sayan2bandw/img29.png', 'Sayan2bandw/img30.png', 'Sayan2bandw/img31.png', 'Sayan2bandw/img32.png', 'Sayan2bandw/img33.png', 'Sayan2bandw/img34.png', 'Sayan2bandw/img35.png', 'Sayan2bandw/img36.png', 'Sayan2bandw/img37.png', 'Sayan2bandw/img38.png', 'Sayan2bandw/img39.png', 'Sayan2ba

In [33]:
Y_test1=[]
for f in files:
    print(f)
    im=cv2.imread(f,cv2.IMREAD_GRAYSCALE)
    Y_test1.append(im)

Sayan2bandw/img0.png
Sayan2bandw/img1.png
Sayan2bandw/img2.png
Sayan2bandw/img3.png
Sayan2bandw/img4.png
Sayan2bandw/img5.png
Sayan2bandw/img6.png
Sayan2bandw/img7.png
Sayan2bandw/img8.png
Sayan2bandw/img9.png
Sayan2bandw/img10.png
Sayan2bandw/img11.png
Sayan2bandw/img12.png
Sayan2bandw/img13.png
Sayan2bandw/img14.png
Sayan2bandw/img15.png
Sayan2bandw/img16.png
Sayan2bandw/img17.png
Sayan2bandw/img18.png
Sayan2bandw/img19.png
Sayan2bandw/img20.png
Sayan2bandw/img21.png
Sayan2bandw/img22.png
Sayan2bandw/img23.png
Sayan2bandw/img24.png
Sayan2bandw/img25.png
Sayan2bandw/img26.png
Sayan2bandw/img27.png
Sayan2bandw/img28.png
Sayan2bandw/img29.png
Sayan2bandw/img30.png
Sayan2bandw/img31.png
Sayan2bandw/img32.png
Sayan2bandw/img33.png
Sayan2bandw/img34.png
Sayan2bandw/img35.png
Sayan2bandw/img36.png
Sayan2bandw/img37.png
Sayan2bandw/img38.png
Sayan2bandw/img39.png
Sayan2bandw/img40.png
Sayan2bandw/img41.png
Sayan2bandw/img42.png
Sayan2bandw/img43.png
Sayan2bandw/img44.png
Sayan2bandw/img45.pn

In [34]:
y_test1=np.array(Y_test1)
print(y_test1)

[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [255 255 255 ...   0   0   0]
  [255 255 255 ...   0   0   0]
  [255 255 255 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

In [35]:
y_test1.resize(2040,2304)


In [36]:
print(y_test1[12,:])

y_test1=y_test1/255

[255 255 255 ... 255 255 255]


In [37]:
l2=model.predict(x_test1)
print(y[12,:])

[1. 1. 1. ... 1. 1. 1.]


In [38]:
scores2 = model.evaluate(x_test1,y_test1, verbose=1)

2040/2040 [==============================] - 0s 188us/step


In [39]:
print(scores2)

[1.3409117088598363, 0.667785140579822]


In [40]:
labels2 = (l2 >0.5).astype(np.int)


In [41]:
print (labels2[0,:])

[1 1 1 ... 1 1 1]


In [42]:
labels2.resize(2040,48,48)

In [43]:
print (y_test1[0,:])


[0. 0. 0. ... 0. 0. 0.]


In [44]:
final2=np.ndarray((1920,2448))
final2.shape

(1920, 2448)

In [45]:
z=0
y1=0
for k in range(0,40):
    for l in range(0,51):
        for i in range(0,48):
            for j in range(0,48):
                final2[i+y1][j+l*48]=labels2[z][i][j]
        z=z+1
    y1=k*48
print(z)
print(y1)


2040
1872


In [48]:
cv2.imwrite("filetrain11.png",final2)

True

In [46]:
final2=final2*255


In [47]:
print(labels2[0,:,:])

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [247]:
z1=0
for i in range(48,96):
    for j in range(0,48):
        if(final2[i][j]==1):
            z1=z1+1
            

In [248]:
print(z1)

2304


In [250]:
np.count_nonzero(labels2[51,:])

2304