In [16]:
import cv2
img=cv2.imread('1/270.png')

print(img)           
    

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [17]:
i=0
for r in range(0,img.shape[0],48):
    for c in range(0,img.shape[1],48):
        cv2.imwrite(f"Rot_Sayanbandw270/270_{i}.png",img[r:r+48, c:c+48,:])
        i=i+1

In [3]:
folder_path = 'Sayan10'


In [4]:
import glob
files=sorted(glob.glob("Sayan2pc/*.png"))

In [5]:
for f in files:
    print(f)

Sayan2pc/0.png
Sayan2pc/1.png
Sayan2pc/10.png
Sayan2pc/100.png
Sayan2pc/1000.png
Sayan2pc/1001.png
Sayan2pc/1002.png
Sayan2pc/1003.png
Sayan2pc/1004.png
Sayan2pc/1005.png
Sayan2pc/1006.png
Sayan2pc/1007.png
Sayan2pc/1008.png
Sayan2pc/1009.png
Sayan2pc/101.png
Sayan2pc/1010.png
Sayan2pc/1011.png
Sayan2pc/1012.png
Sayan2pc/1013.png
Sayan2pc/1014.png
Sayan2pc/1015.png
Sayan2pc/1016.png
Sayan2pc/1017.png
Sayan2pc/1018.png
Sayan2pc/1019.png
Sayan2pc/102.png
Sayan2pc/1020.png
Sayan2pc/1021.png
Sayan2pc/1022.png
Sayan2pc/1023.png
Sayan2pc/1024.png
Sayan2pc/1025.png
Sayan2pc/1026.png
Sayan2pc/1027.png
Sayan2pc/1028.png
Sayan2pc/1029.png
Sayan2pc/103.png
Sayan2pc/1030.png
Sayan2pc/1031.png
Sayan2pc/1032.png
Sayan2pc/1033.png
Sayan2pc/1034.png
Sayan2pc/1035.png
Sayan2pc/1036.png
Sayan2pc/1037.png
Sayan2pc/1038.png
Sayan2pc/1039.png
Sayan2pc/104.png
Sayan2pc/1040.png
Sayan2pc/1041.png
Sayan2pc/1042.png
Sayan2pc/1043.png
Sayan2pc/1044.png
Sayan2pc/1045.png
Sayan2pc/1046.png
Sayan2pc/1047.png
Sayan

In [9]:
y=[]
files2 = sorted(glob.glob ("Sayanbandw/*.png"))
for myFile in files2:
    im=cv2.imread(myFile,cv2.IMREAD_GRAYSCALE)
    y.append(im)

In [10]:
import numpy as np


In [11]:
np.array(y).shape

(2040, 48, 48)

In [12]:
z=np.array(y)

In [13]:
z.shape

(2040, 48, 48)

In [14]:
z.resize([2040,2304])

In [21]:
z.shape

(2040, 2304)

In [15]:
print(z)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]


In [16]:
z=z/255.0

In [17]:
print(z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]


In [18]:
import cv2
import glob
import numpy as np
X_data=[]
files=sorted(glob.glob("Sayan/*.png"))
for f in files:
    print(f)
    im=cv2.imread(f)
    X_data.append(im)
files1=sorted(glob.glob("Sayanp/*.png"))
for f1 in files1:
    print(f1)
    im1=cv2.imread(f1)
    X_data.append(im1)
print('X_data shape:', np.array(X_data).shape)

Sayan/img0.png
Sayan/img1.png
Sayan/img10.png
Sayan/img100.png
Sayan/img1000.png
Sayan/img1001.png
Sayan/img1002.png
Sayan/img1003.png
Sayan/img1004.png
Sayan/img1005.png
Sayan/img1006.png
Sayan/img1007.png
Sayan/img1008.png
Sayan/img1009.png
Sayan/img101.png
Sayan/img1010.png
Sayan/img1011.png
Sayan/img1012.png
Sayan/img1013.png
Sayan/img1014.png
Sayan/img1015.png
Sayan/img1016.png
Sayan/img1017.png
Sayan/img1018.png
Sayan/img1019.png
Sayan/img102.png
Sayan/img1020.png
Sayan/img1021.png
Sayan/img1022.png
Sayan/img1023.png
Sayan/img1024.png
Sayan/img1025.png
Sayan/img1026.png
Sayan/img1027.png
Sayan/img1028.png
Sayan/img1029.png
Sayan/img103.png
Sayan/img1030.png
Sayan/img1031.png
Sayan/img1032.png
Sayan/img1033.png
Sayan/img1034.png
Sayan/img1035.png
Sayan/img1036.png
Sayan/img1037.png
Sayan/img1038.png
Sayan/img1039.png
Sayan/img104.png
Sayan/img1040.png
Sayan/img1041.png
Sayan/img1042.png
Sayan/img1043.png
Sayan/img1044.png
Sayan/img1045.png
Sayan/img1046.png
Sayan/img1047.png
Sayan

Sayan/img824.png
Sayan/img825.png
Sayan/img826.png
Sayan/img827.png
Sayan/img828.png
Sayan/img829.png
Sayan/img83.png
Sayan/img830.png
Sayan/img831.png
Sayan/img832.png
Sayan/img833.png
Sayan/img834.png
Sayan/img835.png
Sayan/img836.png
Sayan/img837.png
Sayan/img838.png
Sayan/img839.png
Sayan/img84.png
Sayan/img840.png
Sayan/img841.png
Sayan/img842.png
Sayan/img843.png
Sayan/img844.png
Sayan/img845.png
Sayan/img846.png
Sayan/img847.png
Sayan/img848.png
Sayan/img849.png
Sayan/img85.png
Sayan/img850.png
Sayan/img851.png
Sayan/img852.png
Sayan/img853.png
Sayan/img854.png
Sayan/img855.png
Sayan/img856.png
Sayan/img857.png
Sayan/img858.png
Sayan/img859.png
Sayan/img86.png
Sayan/img860.png
Sayan/img861.png
Sayan/img862.png
Sayan/img863.png
Sayan/img864.png
Sayan/img865.png
Sayan/img866.png
Sayan/img867.png
Sayan/img868.png
Sayan/img869.png
Sayan/img87.png
Sayan/img870.png
Sayan/img871.png
Sayan/img872.png
Sayan/img873.png
Sayan/img874.png
Sayan/img875.png
Sayan/img876.png
Sayan/img877.png
Sa

Sayanp/img873.png
Sayanp/img874.png
Sayanp/img875.png
Sayanp/img876.png
Sayanp/img877.png
Sayanp/img878.png
Sayanp/img879.png
Sayanp/img88.png
Sayanp/img880.png
Sayanp/img881.png
Sayanp/img882.png
Sayanp/img883.png
Sayanp/img884.png
Sayanp/img885.png
Sayanp/img886.png
Sayanp/img887.png
Sayanp/img888.png
Sayanp/img889.png
Sayanp/img89.png
Sayanp/img890.png
Sayanp/img891.png
Sayanp/img892.png
Sayanp/img893.png
Sayanp/img894.png
Sayanp/img895.png
Sayanp/img896.png
Sayanp/img897.png
Sayanp/img898.png
Sayanp/img899.png
Sayanp/img9.png
Sayanp/img90.png
Sayanp/img900.png
Sayanp/img901.png
Sayanp/img902.png
Sayanp/img903.png
Sayanp/img904.png
Sayanp/img905.png
Sayanp/img906.png
Sayanp/img907.png
Sayanp/img908.png
Sayanp/img909.png
Sayanp/img91.png
Sayanp/img910.png
Sayanp/img911.png
Sayanp/img912.png
Sayanp/img913.png
Sayanp/img914.png
Sayanp/img915.png
Sayanp/img916.png
Sayanp/img917.png
Sayanp/img918.png
Sayanp/img919.png
Sayanp/img92.png
Sayanp/img920.png
Sayanp/img921.png
Sayanp/img922.png

In [19]:
x=np.array(X_data)

In [3]:
import tensorflow as tf
from keras.layers import *
from keras.models import Model,Sequential


Using TensorFlow backend.


In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),strides=(1,1),activation='relu',padding='same',input_shape=(48,48,3)))
model.add(Conv2D(64,(1,1),activation='relu',padding='same'))
model.add(SeparableConv2D(64,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(SeparableConv2D(128,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(SeparableConv2D(256,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(SeparableConv2D(256,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(SeparableConv2D(512,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(SeparableConv2D(1024,(3,3),padding="same",activation='relu'))
model.add(BatchNormalization(axis=-1))
model.add(MaxPooling2D(pool_size=(2,2),strides=None))
model.add(Flatten())
model.add(Dense(2304,activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [1]:
model.compile(optimizer='adam',loss="categorical_crossentropy",metrics=['accuracy'])

NameError: name 'model' is not defined